#include "Z80.h"

#include <cstring>
#include <functional>
#include <stdexcept>


struct Instruction {
	const char* name;
	uint8_t cycleCount;
	uint8_t instructionLength;
	union
	{
		void (*op0)(void);
		void (*op1)(uint8_t);
		void (*op2)(uint16_t);
	};
};

void Z80::Reset()
{
	memset(&registers, 0u, sizeof Registers);
}

static void unimplemented_op0(void)
{
	throw std::logic_error("Function not yet implemented");
}

static void unimplemented_op1(uint8_t)
{
	throw std::logic_error("Function not yet implemented");
}

static void unimplemented_op2(uint16_t)
{
	throw std::logic_error("Function not yet implemented");
}

void Z80::Clock()
{
	auto instruction = Fetch();
	//instruction();
	//timer += instruction.time;
	registers.pc++;
}

int Z80::Fetch()
{
	auto instruction = memory.read_8(registers.pc);
	return int();
}

// instruction table is a modified version of: https://cturt.github.io/cinoop.html

const struct Instruction instructions[256] = {
	{ "NOP",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD BC, 0x%04X",				6,	3,	{ .op2 = unimplemented_op2 }},
	{ "LD (BC), A",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "INC BC",						4,	1,	{ .op0 = unimplemented_op0 }},
	{ "INC B",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "DEC B",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD B, 0x%02X",				4,	2,	{ .op1 = unimplemented_op1 }},
	{ "RLCA",						4,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD (0x%04X), SP",			10,	3,	{ .op2 = unimplemented_op2 }},
	{ "ADD HL, BC",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD A, (BC)",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "DEC BC",						4,	1,	{ .op0 = unimplemented_op0 }},
	{ "INC C",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "DEC C",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD C, 0x%02X",				4,	2,	{ .op1 = unimplemented_op1 }},
	{ "RRCA",						4,	1,	{ .op0 = unimplemented_op0 }},
	{ "STOP",						2,	2,	{ .op1 = unimplemented_op1 }},
	{ "LD DE, 0x%04X",				6,	3,	{ .op2 = unimplemented_op2 }},
	{ "LD (DE), A",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "INC DE",						4,	1,	{ .op0 = unimplemented_op0 }},
	{ "INC D",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "DEC D",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD D, 0x%02X",				4,	2,	{ .op1 = unimplemented_op1 }},
	{ "RLA",						4,	1,	{ .op0 = unimplemented_op0 }},
	{ "JR 0x%02X",					4,	2,	{ .op1 = unimplemented_op1 }},
	{ "ADD HL, DE",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD A, (DE)",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "DEC DE",						4,	1,	{ .op0 = unimplemented_op0 }},
	{ "INC E",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "DEC E",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD E, 0x%02X",				4,	2,	{ .op1 = unimplemented_op1 }},
	{ "RRA",						4,	1,	{ .op0 = unimplemented_op0 }},
	{ "JR NZ, 0x%02X",				0,	2,	{ .op1 = unimplemented_op1 }},
	{ "LD HL, 0x%04X",				6,	3,	{ .op2 = unimplemented_op2 }},
	{ "LDI (HL), A",				4,	1,	{ .op0 = unimplemented_op0 }},
	{ "INC HL",						4,	1,	{ .op0 = unimplemented_op0 }},
	{ "INC H",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "DEC H",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD H, 0x%02X",				4,	2,	{ .op1 = unimplemented_op1 }},
	{ "DAA",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "JR Z, 0x%02X",				0,	2,	{ .op1 = unimplemented_op1 }},
	{ "ADD HL, HL",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "LDI A, (HL)",				4,	1,	{ .op0 = unimplemented_op0 }},
	{ "DEC HL",						4,	1,	{ .op0 = unimplemented_op0 }},
	{ "INC L",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "DEC L",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD L, 0x%02X",				4,	2,	{ .op1 = unimplemented_op1 }},
	{ "CPL",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "JR NC, 0x%02X",				4,	2,	{ .op1 = unimplemented_op1 }},
	{ "LD SP, 0x%04X",				6,	3,	{ .op2 = unimplemented_op2 }},
	{ "LDD (HL), A",				4,	1,	{ .op0 = unimplemented_op0 }},
	{ "INC SP",						4,	1,	{ .op0 = unimplemented_op0 }},
	{ "INC (HL)",					6,	1,	{ .op0 = unimplemented_op0 }},
	{ "DEC (HL)",					6,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD (HL), 0x%02X",			6,	2,	{ .op1 = unimplemented_op1 }},
	{ "SCF",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "JR C, 0x%02X",				0,	2,	{ .op1 = unimplemented_op1 }},
	{ "ADD HL, SP",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "LDD A, (HL)",				4,	1,	{ .op0 = unimplemented_op0 }},
	{ "DEC SP",						4,	1,	{ .op0 = unimplemented_op0 }},
	{ "INC A",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "DEC A",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD A, 0x%02X",				4,	2,	{ .op1 = unimplemented_op1 }},
	{ "CCF",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD B, B",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD B, C",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD B, D",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD B, E",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD B, H",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD B, L",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD B, (HL)",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD B, A",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD C, B",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD C, C",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD C, D",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD C, E",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD C, H",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD C, L",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD C, (HL)",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD C, A",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD D, B",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD D, C",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD D, D",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD D, E",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD D, H",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD D, L",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD D, (HL)",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD D, A",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD E, B",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD E, C",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD E, D",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD E, E",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD E, H",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD E, L",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD E, (HL)",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD E, A",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD H, B",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD H, C",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD H, D",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD H, E",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD H, H",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD H, L",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD H, (HL)",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD H, A",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD L, B",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD L, C",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD L, D",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD L, E",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD L, H",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD L, L",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD L, (HL)",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD L, A",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD (HL), B",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD (HL), C",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD (HL), D",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD (HL), E",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD (HL), H",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD (HL), L",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "HALT",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD (HL), A",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD A, B",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD A, C",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD A, D",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD A, E",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD A, H",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD A, L",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD A, (HL)",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD A, A",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "ADD A, B",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "ADD A, C",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "ADD A, D",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "ADD A, E",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "ADD A, H",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "ADD A, L",					2,	1,	{ .op0 = unimplemented_op0 }},
	{ "ADD A, (HL)",				4,	1,	{ .op0 = unimplemented_op0 }},
	{ "ADD A",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "ADC B",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "ADC C",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "ADC D",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "ADC E",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "ADC H",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "ADC L",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "ADC (HL)",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "ADC A",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "SUB B",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "SUB C",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "SUB D",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "SUB E",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "SUB H",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "SUB L",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "SUB (HL)",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "SUB A",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "SBC B",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "SBC C",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "SBC D",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "SBC E",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "SBC H",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "SBC L",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "SBC (HL)",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "SBC A",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "AND B",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "AND C",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "AND D",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "AND E",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "AND H",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "AND L",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "AND (HL)",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "AND A",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "XOR B",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "XOR C",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "XOR D",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "XOR E",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "XOR H",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "XOR L",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "XOR (HL)",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "XOR A",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "OR B",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "OR C",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "OR D",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "OR E",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "OR H",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "OR L",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "OR (HL)",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "OR A",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "CP B",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "CP C",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "CP D",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "CP E",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "CP H",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "CP L",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "CP (HL)",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "CP A",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "RET NZ",						0,	1,	{ .op0 = unimplemented_op0 }},
	{ "POP BC",						6,	1,	{ .op0 = unimplemented_op0 }},
	{ "JP NZ, 0x%04X",				0,	3,	{ .op2 = unimplemented_op2 }},
	{ "JP 0x%04X",					6,	3,	{ .op2 = unimplemented_op2 }},
	{ "CALL NZ, 0x%04X",			0,	3,	{ .op2 = unimplemented_op2 }},
	{ "PUSH BC",					8,	1,	{ .op0 = unimplemented_op0 }},
	{ "ADD A, 0x%02X",				4,	2,	{ .op1 = unimplemented_op1 }},
	{ "RST 0x00",					8,	1,	{ .op0 = unimplemented_op0 }},
	{ "RET Z",						0,	1,	{ .op0 = unimplemented_op0 }},
	{ "RET",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "JP Z, 0x%04X",				0,	3,	{ .op2 = unimplemented_op2 }},
	{ "CB %02X",					0,	2,	{ .op1 = unimplemented_op1 }},
	{ "CALL Z, 0x%04X",				0,	3,	{ .op2 = unimplemented_op2 }},
	{ "CALL 0x%04X",				6,	3,	{ .op2 = unimplemented_op2 }},
	{ "ADC 0x%02X",					4,	2,	{ .op1 = unimplemented_op1 }},
	{ "RST 0x08",					8,	1,	{ .op0 = unimplemented_op0 }},
	{ "RET NC",						0,	1,	{ .op0 = unimplemented_op0 }},
	{ "POP DE",						6,	1,	{ .op0 = unimplemented_op0 }},
	{ "JP NC, 0x%04X",				0,	3,	{ .op2 = unimplemented_op2 }},
	{ "UNKNOWN",					0,	1,	{ .op0 = unimplemented_op0 }},
	{ "CALL NC, 0x%04X",			0,	3,	{ .op2 = unimplemented_op2 }},
	{ "PUSH DE",					8,	1,	{ .op0 = unimplemented_op0 }},
	{ "SUB 0x%02X",					4,	2,	{ .op1 = unimplemented_op1 }},
	{ "RST 0x10",					8,	1,	{ .op0 = unimplemented_op0 }},
	{ "RET C",						0,	1,	{ .op0 = unimplemented_op0 }},
	{ "RETI",						8,	1,	{ .op0 = unimplemented_op0 }},
	{ "JP C, 0x%04X",				0,	3,	{ .op2 = unimplemented_op2 }},
	{ "UNKNOWN",					0,	1,	{ .op0 = unimplemented_op0 }},
	{ "CALL C, 0x%04X",				0,	3,	{ .op2 = unimplemented_op2 }},
	{ "UNKNOWN",					0,	1,	{ .op0 = unimplemented_op0 }},
	{ "SBC 0x%02X",					4,	2,	{ .op1 = unimplemented_op1 }},
	{ "RST 0x18",					8,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD (0xFF00 + 0x%02X), A",	6,	2,	{ .op1 = unimplemented_op1 }},
	{ "POP HL",						6,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD (0xFF00 + C), A",			4,	1,	{ .op0 = unimplemented_op0 }},
	{ "UNKNOWN",					0,	1,	{ .op0 = unimplemented_op0 }},
	{ "UNKNOWN",					0,	1,	{ .op0 = unimplemented_op0 }},
	{ "PUSH HL",					8,	1,	{ .op0 = unimplemented_op0 }},
	{ "AND 0x%02X",					4,	2,	{ .op1 = unimplemented_op1 }},
	{ "RST 0x20",					8,	1,	{ .op0 = unimplemented_op0 }},
	{ "ADD SP,0x%02X",				8,	2,	{ .op1 = unimplemented_op1 }},
	{ "JP HL",						2,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD (0x%04X), A",				8,	3,	{ .op2 = unimplemented_op2 }},
	{ "UNKNOWN",					0,	1,	{ .op0 = unimplemented_op0 }},
	{ "UNKNOWN",					0,	1,	{ .op0 = unimplemented_op0 }},
	{ "UNKNOWN",					0,	1,	{ .op0 = unimplemented_op0 }},
	{ "XOR 0x%02X",					4,	2,	{ .op1 = unimplemented_op1 }},
	{ "RST 0x28",					8,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD A, (0xFF00 + 0x%02X)",	6,	2,	{ .op1 = unimplemented_op1 }},
	{ "POP AF",						6,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD A, (0xFF00 + C)",			4,	1,	{ .op0 = unimplemented_op0 }},
	{ "DI",							2,	1,	{ .op0 = unimplemented_op0 }},
	{ "UNKNOWN",					0,	1,	{ .op0 = unimplemented_op0 }},
	{ "PUSH AF",					8,	1,	{ .op0 = unimplemented_op0 }},
	{ "OR 0x%02X",					4,	2,	{ .op1 = unimplemented_op1 }},
	{ "RST 0x30",					8,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD HL, SP+0x%02X",			6,	2,	{ .op1 = unimplemented_op1 }},
	{ "LD SP, HL",					4,	1,	{ .op0 = unimplemented_op0 }},
	{ "LD A, (0x%04X)",				8,	3,	{ .op2 = unimplemented_op2 }},
	{ "EI",							2,	1,	{ .op0 = unimplemented_op0 }},
	{ "UNKNOWN",					0,	1,	{ .op0 = unimplemented_op0 }},
	{ "UNKNOWN",					0,	1,	{ .op0 = unimplemented_op0 }},
	{ "CP 0x%02X",					4,	2,	{ .op1 = unimplemented_op1 }},
	{ "RST 0x38",					8,	1,	{ .op0 = unimplemented_op0 }}
};